#include </Users/PremBhatia1/stdc.h>

using namespace std;

// Return length of longest palindrome possible (generated by rearrangement of alphabets)
int getLenLongestPalindrome(string str)
{
    int pairs = 0;
    std::map<char, int> mp;
    for (int i = 0; i < str.size(); i++)
    {
        if (mp.count(str[i]) == 1)
        {
            pairs++;
            mp.erase(str[i]);
        }
        else
        {
            mp.insert({str[i], 1});
        }
    }
    return pairs * 2 + (mp.size() > 0 ? 1 : 0);
}

int main()
{
    string str = "abcdabcdkkklhi";
    cout << getLenLongestPalindrome(str) << endl;
}